### ISSUE TITLE
word wrap for tooltip

### ISSUE THREAD

**Issue by thinkTank15** [vue-bulma/tooltip#3]
Is there a way to wrap the text in next line in the tooltip?

**Comment by luventa** [comment]
Please check the related commit. It provided auto word wrap fix.
If you need manual word wrap, please reopen this issue.
I will publish this component soon.

**Comment by thinkTank15** [comment]
Thanks that worked :)
just a follow up question, I am passing an html string into tooltip, 
something like this: `<tooltip label="<h4>something</h4>">`
any idea on how can this be rendered?

**Comment by luventa** [comment]
nope.. vue-bulma-tooltip is using [hint.css](https://github.com/chinchang/hint.css). Hint.css does not implement this functionality yet.
related issue of hint.css: [Ability to show markup inside tooltips](https://github.com/chinchang/hint.css/issues/154)
