### ISSUE TITLE
TypeError: Cannot set property 'attrs' of undefined

### ISSUE THREAD

**Issue by adambiggs** [vue-bulma/tooltip#4]
I tried following the readme example, but I keep getting `TypeError: Cannot set property 'attrs' of undefined` when trying to render `<tooltip>` components.

**Comment by luventa** [comment]
Did you change anything in `tooltip`?
No matter what you put into the `tooltip` element, it must contains a class attr.

```vue
  <tooltip label="This is title" placement="top-right">
    <span class="a">top-right</span>
  </tooltip>
```

or

```vue
<tooltip label="top-right" placement="top-right">
  <button class="button is-primary has-text-centered">
    <span>top-right<a>test</a></span>
  </button>
</tooltip>
```
