### ISSUE TITLE
Font color for type `warning`

### ISSUE THREAD

**Issue by marekkaczkowski** [vue-bulma/tooltip#5]
Easy-peasy to fix :neckbeard:
Text for tooltip type `warning` should be dark.

![bulma_tooltip_022817_013656_pm](https://cloud.githubusercontent.com/assets/273831/23405606/59e71094-fdbb-11e6-85c6-36ee41258225.jpg)

**Comment by luventa** [comment]
yes, fixed. thanks for reporting this :)
