### ISSUE TITLE
ERROR in static/js/vendor.90b0fa6ef7bb953cc3ff.js from UglifyJs

### ISSUE THREAD

**Issue by holic-cl** [vue-bulma/tooltip#6]
Hi, i was having this issue with the tooltip, when i make a npm run build i got this error:
```
ERROR in static/js/vendor.90b0fa6ef7bb953cc3ff.js from UglifyJs
Unexpected token: operator (>) [static/js/vendor.90b0fa6ef7bb953cc3ff.js:20501,24]
```

I am using this:
* "vue-bulma-tooltip": "^1.0.1"
* "vue-loader": "^10.3.0"
* "webpack": "^2.2.1"

At the moment i can solve this by editing the webpack config (webpack.base.conf.js):
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-bulma-tooltip')]
      },
```

Greetings.

**Comment by luventa** [comment]
Yes @holic-cl , this component is not compiled by babel yet.
Babel loader config in vue-admin could be helpful:
```
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: YOU_DIR,
  exclude: [new RegExp(`node_modules\\${path.sep}(?!vue-bulma-.*)`)]
}
```

We will package all vue-bulma components later. Thanks!
