### ISSUE TITLE
CSS classes lost

### ISSUE THREAD

**Issue by KKSzymanowski** [vue-bulma/tooltip#8]
First of all, thanks for all the components, they're great.
I have one issue with the tooltip. If I for example want to create a tooltip for a button:
```html
<tooltip label="This is title" placement="top-right">
    <button class="button">
        Button
    </button>
</tooltip>
```
It all looks fine:
![image](https://cloud.githubusercontent.com/assets/13980973/26399097/f1003f3e-407b-11e7-9283-f034b1b15da1.png)

But when I want to apply dynamic classes:
```html
<tooltip label="This is title" placement="top-right">
    <button :class="{button: true}">
        Button
    </button>
</tooltip>
```
or
```html
<tooltip label="This is title" placement="top-right">
    <button :class="buttonClass">
        Button
    </button>
</tooltip>
```
it loses styling:

![image](https://cloud.githubusercontent.com/assets/13980973/26399169/39cb0c62-407c-11e7-8d8b-5cdf9d927904.png)

and the button markup looks like this:
![image](https://cloud.githubusercontent.com/assets/13980973/26399323/d08181a4-407c-11e7-9d9a-977bc347ff1e.png)

I'm using Vue 2.3.3, vue-bulma-tooltip 1.0.3 and this issue appears in every browser I have installed(Chrome, Firefox, MS Edge).

Is it possible to fix this?
Thanks.

**Comment by natiz** [comment]
Same here:
"vue": "^2.3.3",
"vue-bulma-tooltip": "^1.0.3",

It's not just classes, looks like for every binding (I noticed it in `:disabled="..."`

**Comment by daikazu** [comment]
I was able to workaround this issue using the following:

```js
<tooltip label="This is title" placement="top-right">
    <div class="">
        <button :class="{button: true}">
            Button
        </button>
    </div>
</tooltip>
```
The wrapper element needed a empty `class=` attribute for this to work.

**Comment by natiz** [comment]
I added a PR - @luventa @fundon - can you please have a look?

**Comment by KKSzymanowski** [comment]
Thanks, @natiz

**Comment by luventa** [comment]
merged. #9 to fix this. Thanks @natiz . I will publish new version soon.
